name: Run Selenium Demo

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'  # हर 30 मिनट पर (यदि चाहो)

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Chromium & chromedriver
        run: |
          sudo apt update
          sudo apt install -y chromium-browser chromium-chromedriver

      - name: Run script
        env:
          FB_USER: ${{ secrets.FB_USER }}
          FB_PASS: ${{ secrets.FB_PASS }}
          TARGET_ID: ${{ secrets.TARGET_ID }}
        run: python send_file.py
